### PR TITLE
Feature: Newsletter

### PR DESCRIPTION
**Pull request by JanKrb**
Solving issue https://github.com/KrbDevelopment/Articly-Backend/issues/1

### CODE REVIEW

**Comment by NinoKrb** [comment]
Please send a message when a post is created in a bookmarked category

**Comment by JanKrb** [comment]
> Please send a message when a post is created in a bookmarked category

Solved in https://github.com/KrbDevelopment/Articly-Backend/commit/d02ae53f54c378ee424ad3594e15e0f6e752d755.

**Comment by NinoKrb** [comment]
An email is sent although the mail is not verified. Please make sure that the email is sent only when authorizing!

**Comment by JanKrb** [comment]
> An email is sent although the mail is not verified. Please make sure that the email is sent only when authorizing!

Solved in https://github.com/KrbDevelopment/Articly-Backend/commit/f733d7aa1398c268efcc48adbefee934c648b3fa

**Comment by NinoKrb** [comment]
When verifying the post, the user receives two emails, one that the post has been updated and the other that it has been created. Please send only the correct email when creating.

**Comment by JanKrb** [comment]
> When verifying the post, the user receives two emails, one that the post has been updated and the other that it has been created. Please send only the correct email when creating.

Solved in https://github.com/KrbDevelopment/Articly-Backend/commit/16831a1c47f64b8f2e797a9cd44a44db9da9082e

**Pull request merged**
